doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'  # Укажите драйвер для вашей базы данных, например, pdo_pgsql для PostgreSQL
        server_version: '16' # Укажите вашу версию базы данных, например, 13 для PostgreSQL
        charset: UTF8

    orm:
        controller_resolver:
            auto_mapping: false

        # Генерация прокси-классов для сущностей (по умолчанию true)
        auto_generate_proxy_classes: true

        # Прокси-классы будут сохранены в папке src/Entity
        proxy_dir: '%kernel.project_dir%/var/doctrine/proxies'
        proxy_namespace: 'DoctrineProxies'



        # Список сущностей и их маппинг
        entity_managers:
            default:
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

        # lazy_loading для прокси-объектов
        enable_lazy_ghost_objects: true



when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
