doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '16'
        charset: UTF8

    orm:
        controller_resolver:
            auto_mapping: false

        auto_generate_proxy_classes: true

        proxy_dir: '%kernel.project_dir%/var/doctrine/proxies'
        proxy_namespace: 'DoctrineProxies'


        entity_managers:
            default:
                naming_strategy: 'Doctrine\ORM\Mapping\UnderscoreNamingStrategy'
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

        enable_lazy_ghost_objects: true


when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
